apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: kube-system
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook-yakup
        image: 8.208.76.23:5050/root/cv/webhook-yakup
        ports:
        - containerPort: 8443
        volumeMounts:
        - readOnly: true
          mountPath: /app/certs
          name: certs
      volumes:
      - name: certs
        secret:
          secretName: cpu-limit-certs